import faker from 'faker';
import uniqueRandomArray from 'unique-random-array';
import { Clusters } from '../../../api/Clusters/Clusters';
import { seedOrgType, seedStages, seedTags } from '../../../modules/helpers';



// CREATE RANDOM CLUSTER HELPER
// ========================================================
let clustersQuery = Clusters.find().fetch();

let mappedClusters = clustersQuery.map(function(item){
	return item._id;
});

let randomCluster = uniqueRandomArray(mappedClusters);

let randomSeedTag = uniqueRandomArray(seedTags);


// GET THE ADMIN USER TO BE USED AS OWNER FOR SEEDED ORGANIZATION RECORDS
// ========================================================

let admin = Meteor.users.findOne({roles: {$in: ['advisor']}});

export const seedServiceTypes = [
  { value: 'businessPlanning', label: 'Business Planning' },
  { value: 'financialManagement', label: 'Financial Management' },
  { value: 'funding', label: 'Funding' },
  { value: 'legalAssistance', label: 'Legal Assistance' },
  { value: 'salesAndMarketing', label: 'Sales & Marketing' },
  { value: 'researchAndDev', label: 'Research & Development' },
  { value: 'realEstate', label: 'Real Estate' },
  { value: 'workforce', label: 'Workforce Development' },
]





// CREATE RANDOM CLUSTER HELPER
// ========================================================
let orgs = [
	{
		_id: 1,
		title: 'University Department of Technology & Engineering',
		location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
		description: faker.lorem.sentence(),
		serviceTypes: ['researchAndDev', 'workforce', 'businessPlanning'],
		orgType: 'university department',
		createdAt: new Date(),
		updatedAt: new Date(),
		ownerId: admin._id,
		tags: [randomSeedTag(), randomSeedTag() ],
		resourceItems: [
			{
				title: `3D Printing Prototype Consulting`,
				description: 'Have an idea for a hardware or other product? Connect with engineering students to recieve consulting and access to the universitys 3D printing resources',
				location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
				resourceType: 'service',
				serviceTypes: ['researchAndDev', 'workforce'],
				stages: ['startup'],
				clusters: [randomCluster(), randomCluster()],
				schemaVersion: 0,
				//base
				createdAt: new Date(),
				updatedAt: new Date(),
				ownerId: admin._id,
				deleted: false,
			},
			{
				title: `Free Websites and Landing Pages`,
				description: faker.lorem.sentence(),
				location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
				resourceType: 'incentive',
				stages: ['existing'],
				serviceTypes: ['salesAndMarketing', 'businessPlanning'],
				clusters: [randomCluster(), randomCluster()],
				schemaVersion: 0,
				//base
				createdAt: new Date(),
				updatedAt: new Date(),
				ownerId: admin._id,
				deleted: false,
			}
		],
		event: {
			title: 'Hiring Mechanical Engineers',
			serviceTypes: ['workforce'],
			description: 'fsdafasf',
			location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
			stages: ['startup'],
			clusters: [randomCluster(), randomCluster()],
			tags: [],
			time: '12PM',
			date: faker.date.future(),
			usersAttending: [],
			schemaVersion: 0,
			numberAttending: 0,
			createdAt: new Date(),
			updatedAt: new Date(),
			ownerId: admin._id,
			deleted: false,
		}
	},
	{
		_id: 2,
		title: 'University Department of the Arts',
		location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
		description: faker.lorem.sentence(),
		orgType: 'university department',
		serviceTypes: ['salesAndMarketing'],
		createdAt: new Date(),
		updatedAt: new Date(),
		ownerId: admin._id,
		tags: [randomSeedTag(), randomSeedTag() ],
		resourceItems: [
			{
				title: `Free Company Logos`,
				description: 'Does your company need a logo? The art department has students who need to fill out their portfolio. Come by for a free logo consultation.',
				location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
				resourceType: 'service',
				stages: ['startup', 'existing'],
				serviceTypes: ['salesAndMarketing'],
				clusters: [randomCluster(), randomCluster()],
				schemaVersion: 0,
				//base
				createdAt: new Date(),
				updatedAt: new Date(),
				ownerId: admin._id,
				deleted: false,
			}
		],
		event: {
			title: 'Why Design Matters in Business',
			serviceTypes: ['workforce'],
			description: 'fsdafasf',
			location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
			stages: ['startup'],
			clusters: [randomCluster(), randomCluster()],
			tags: [],
			time: '12PM',
			date: faker.date.future(),
			usersAttending: [],
			schemaVersion: 0,
			numberAttending: 0,
			createdAt: new Date(),
			updatedAt: new Date(),
			ownerId: admin._id,
			deleted: false,
		}
	},
	{
		_id: 3,
		title: 'University Law Department',
		serviceTypes: ['legalAssistance'],
		location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
		description: faker.lorem.sentence(),
		orgType: 'university department',
		createdAt: new Date(),
		updatedAt: new Date(),
		ownerId: admin._id,
		tags: [randomSeedTag(), randomSeedTag() ],
		resourceItems: [
			{
				title: `Free LLC Incorporation`,
				description: 'Time to register your student business? This is a good place to start. The law clinic can consult you and help you get on the path to registering your LLC with the state.',
				location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
				resourceType: 'service',
				stages: ['startup'],
				serviceTypes: ['legalAssistance'],
				clusters: [randomCluster(), randomCluster()],
				schemaVersion: 0,
				//base
				createdAt: new Date(),
				updatedAt: new Date(),
				ownerId: admin._id,
				deleted: false,
			}
		],
		event: {
			title: 'The Dos and Donts of Incorporating',
			serviceTypes: ['legalAssistance'],
			description: 'fsdafasf',
			location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
			stages: ['startup'],
			clusters: [randomCluster(), randomCluster()],
			tags: [],
			time: '12PM',
			date: faker.date.future(),
			usersAttending: [],
			schemaVersion: 0,
			numberAttending: 0,
			createdAt: new Date(),
			updatedAt: new Date(),
			ownerId: admin._id,
			deleted: false,
		}
	},
	{
		_id: 4,
		title: 'University Coworking Space',
		location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
		description: faker.lorem.sentence(),
		serviceTypes: ['realEstate'],
		orgType: 'university affiliate',
		createdAt: new Date(),
		updatedAt: new Date(),
		ownerId: admin._id,
		tags: [randomSeedTag(), randomSeedTag() ],
		resourceItems: [
			{
				title: `Coworking Space for Teams`,
				description: 'Need some space for your team outside of the library or cafeteria? We can help.',
				location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
				resourceType: 'incentive',
				serviceTypes: ['realEstate'],
				stages: ['startup', 'idea'],
				clusters: [randomCluster(), randomCluster()],
				schemaVersion: 0,
				//base
				createdAt: new Date(),
				updatedAt: new Date(),
				ownerId: admin._id,
				deleted: false,
			}
		],
		event: {
			title: 'Working with Teams',
			serviceTypes: ['workforce'],
			description: 'fsdafasf',
			location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
			stages: ['startup'],
			clusters: [randomCluster(), randomCluster()],
			tags: [],
			time: '12PM',
			date: faker.date.future(),
			usersAttending: [],
			schemaVersion: 0,
			numberAttending: 0,
			createdAt: new Date(),
			updatedAt: new Date(),
			ownerId: admin._id,
			deleted: false,
		}
	},
	{
		_id: 5,
		title: 'Local Angel Investment Group',
		serviceTypes: ['funding'],
		location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
		description: faker.lorem.sentence(),
		orgType: 'local business',
		createdAt: new Date(),
		updatedAt: new Date(),
		ownerId: admin._id,
		tags: [randomSeedTag(), randomSeedTag() ],
		resourceItems: [
			{
				title: `Angel Investment`,
				description: faker.lorem.sentence(),
				location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
				resourceType: 'funding',
				stages: ['existing', 'startup', 'idea'],
				clusters: [randomCluster(), randomCluster()],
				schemaVersion: 0,
				//base
				createdAt: new Date(),
				updatedAt: new Date(),
				ownerId: admin._id,
				deleted: false,
			}
		],
		event: {
			title: 'Raising Your First Round of Funding',
			serviceTypes: ['workforce'],
			description: 'fsdafasf',
			location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
			stages: ['startup'],
			clusters: [randomCluster(), randomCluster()],
			tags: [],
			time: '12PM',
			date: faker.date.future(),
			usersAttending: [],
			schemaVersion: 0,
			numberAttending: 0,
			createdAt: new Date(),
			updatedAt: new Date(),
			ownerId: admin._id,
			deleted: false,
		}
	},
	{
	   _id: 5,
	   title: 'University Entreprenuership Center',
	   serviceTypes: ['funding'],
	   location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
	   description: faker.lorem.sentence(),
	   orgType: 'university department',
	   createdAt: new Date(),
		updatedAt: new Date(),
		ownerId: admin._id,
		tags: [randomSeedTag(), randomSeedTag() ],
	   resourceItems: [
			{
				title: `SMB Incentive Program`,
				serviceTypes: ['funding'],
				description: faker.lorem.sentence(),
				location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
				resourceType: 'incentive',
				stages: ['existing'],
				clusters: [randomCluster(), randomCluster()],
				schemaVersion: 0,
				//base
				createdAt: new Date(),
				updatedAt: new Date(),
				ownerId: admin._id,
				deleted: false,
			}
		],
		event: {
			title: 'What to know before you start',
			serviceTypes: ['workforce'],
			description: 'fsdafasf',
			location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
			stages: ['startup'],
			clusters: [randomCluster(), randomCluster()],
			tags: [],
			time: '12PM',
			date: faker.date.future(),
			usersAttending: [],
			schemaVersion: 0,
			numberAttending: 0,
			createdAt: new Date(),
			updatedAt: new Date(),
			ownerId: admin._id,
			deleted: false,
		}
	},
	{
	   	_id: 6,
	   	title: 'Local CDFI',
	   	serviceTypes: ['funding'],
	   	description: faker.lorem.sentence(),
	   	location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
	   	orgType: 'local non-profit',
	   	createdAt: new Date(),
		updatedAt: new Date(),
		ownerId: admin._id,
		tags: [randomSeedTag(), randomSeedTag() ],
	   	resourceItems: [
			{
				title: `Local Business Loans`,
				description: faker.lorem.sentence(),
				location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
				resourceType: 'incentive',
				stages: ['existing'],
				serviceTypes: ['funding'],
				clusters: [randomCluster(), randomCluster()],
				schemaVersion: 0,
				//base
				createdAt: new Date(),
				updatedAt: new Date(),
				ownerId: admin._id,
				deleted: false,
			}
		],
		event: {
			title: 'What to know before you start',
			serviceTypes: ['workforce'],
			description: 'fsdafasf',
			location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
			stages: ['startup'],
			clusters: [randomCluster(), randomCluster()],
			tags: [],
			time: '12PM',
			date: faker.date.future(),
			usersAttending: [],
			schemaVersion: 0,
			numberAttending: 0,
			createdAt: new Date(),
			updatedAt: new Date(),
			ownerId: admin._id,
			deleted: false,
		}
	},
	{
		_id: 8,
		title: 'Local Incubator',
		description: faker.lorem.sentence(),
		location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
		orgType: 'local non-profit',
		createdAt: new Date(),
		updatedAt: new Date(),
		serviceTypes: ['funding'],
		ownerId: admin._id,
		tags: [randomSeedTag(), randomSeedTag() ],
		resourceItems: [
			{
				title: `Accelerator Program`,
				description: faker.lorem.sentence(),
				location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
				resourceType: 'incentive',
				stages: ['existing'],
				clusters: [randomCluster(), randomCluster()],
				schemaVersion: 0,
				//base
				createdAt: new Date(),
				updatedAt: new Date(),
				ownerId: admin._id,
				deleted: false,
			}
		],
		event: {
			title: 'What to know before you start',
			serviceTypes: ['workforce'],
			description: 'fsdafasf',
			location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
			stages: ['startup'],
			clusters: [randomCluster(), randomCluster()],
			tags: [],
			time: '12PM',
			date: faker.date.future(),
			usersAttending: [],
			schemaVersion: 0,
			numberAttending: 0,
			createdAt: new Date(),
			updatedAt: new Date(),
			ownerId: admin._id,
			deleted: false,
		}
	},
	{
		_id: 9,
		title: 'Local SBDC',
		description: faker.lorem.sentence(),
		location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
		orgType: 'other',
		createdAt: new Date(),
		updatedAt: new Date(),
		serviceTypes: ['funding'],
		ownerId: admin._id,
		tags: [randomSeedTag(), randomSeedTag() ],
		resourceItems: [
			{
				title: `Free Business Advisors`,
				description: faker.lorem.sentence(),
				location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
				resourceType: 'incentive',
				stages: ['existing'],
				clusters: [randomCluster(), randomCluster()],
				schemaVersion: 0,
				//base
				createdAt: new Date(),
				updatedAt: new Date(),
				ownerId: admin._id,
				deleted: false,
			}
		],
		event: {
			title: 'What to know before you start',
			serviceTypes: ['workforce'],
			description: 'fsdafasf',
			location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
			stages: ['startup'],
			clusters: [randomCluster(), randomCluster()],
			tags: [],
			time: '12PM',
			date: faker.date.future(),
			usersAttending: [],
			schemaVersion: 0,
			numberAttending: 0,
			createdAt: new Date(),
			updatedAt: new Date(),
			ownerId: admin._id,
			deleted: false,
		}
	},
	{
		_id: 10,
		title: 'Local Bank',
		description: faker.lorem.sentence(),
		location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
		orgType: 'local business',
		createdAt: new Date(),
		serviceTypes: ['funding'],
		updatedAt: new Date(),
		ownerId: admin._id,
		tags: [randomSeedTag(), randomSeedTag() ],
		resourceItems: [
			{
				title: `Small Business Loans`,
				description: faker.lorem.sentence(),
				location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
				resourceType: 'incentive',
				serviceTypes: ['funding'],
				stages: ['existing'],
				clusters: [randomCluster(), randomCluster()],
				schemaVersion: 0,
				//base
				createdAt: new Date(),
				updatedAt: new Date(),
				ownerId: admin._id,
				deleted: false,
			}
		],
		event: {
			title: 'What to know before you start',
			serviceTypes: ['workforce'],
			description: 'fsdafasf',
			location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
			stages: ['startup'],
			clusters: [randomCluster(), randomCluster()],
			tags: [],
			time: '12PM',
			date: faker.date.future(),
			usersAttending: [],
			schemaVersion: 0,
			numberAttending: 0,
			createdAt: new Date(),
			updatedAt: new Date(),
			ownerId: admin._id,
			deleted: false,
		}
	},
	{
		_id: 11,
		title: 'Community Non-Profit',
		description: faker.lorem.sentence(),
		location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
		orgType: 'local non-profit',
		serviceTypes: ['funding'],
		createdAt: new Date(),
		updatedAt: new Date(),
		ownerId: admin._id,
		tags: [randomSeedTag(), randomSeedTag() ],
		resourceItems: [
			{
				title: `Startup of the Year Award`,
				description: faker.lorem.sentence(),
				location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
				resourceType: 'incentive',
				stages: ['existing'],
				serviceTypes: ['funding'],
				clusters: [randomCluster(), randomCluster()],
				schemaVersion: 0,
				//base
				createdAt: new Date(),
				updatedAt: new Date(),
				ownerId: admin._id,
				deleted: false,
			}
		],
		event: {
			title: 'What to know before you start',
			serviceTypes: ['workforce'],
			description: 'fsdafasf',
			location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
			stages: ['startup'],
			clusters: [randomCluster(), randomCluster()],
			tags: [],
			time: '12PM',
			date: faker.date.future(),
			usersAttending: [],
			schemaVersion: 0,
			numberAttending: 0,
			createdAt: new Date(),
			updatedAt: new Date(),
			ownerId: admin._id,
			deleted: false,
		}
	},
	{
		_id: 12,
		title: 'State Economic Department',
		description: faker.lorem.sentence(),
		location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
		orgType: 'state government',
		createdAt: new Date(),
		updatedAt: new Date(),
		serviceTypes: ['funding'],
		ownerId: admin._id,
		tags: [randomSeedTag(), randomSeedTag() ],
		resourceItems: [
			{
				title: `Manufacturing Incentive Program`,
				description: faker.lorem.sentence(),
				location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
				resourceType: 'incentive',
				stages: ['existing'],
				clusters: [randomCluster(), randomCluster()],
				schemaVersion: 0,
				//base
				createdAt: new Date(),
				updatedAt: new Date(),
				ownerId: admin._id,
				deleted: false,
			}
		],
		event: {
			title: 'What to know before you start',
			serviceTypes: ['workforce'],
			description: 'fsdafasf',
			location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
			stages: ['startup'],
			clusters: [randomCluster(), randomCluster()],
			tags: [],
			time: '12PM',
			date: faker.date.future(),
			usersAttending: [],
			schemaVersion: 0,
			numberAttending: 0,
			createdAt: new Date(),
			updatedAt: new Date(),
			ownerId: admin._id,
			deleted: false,
		}
	},
	{
		_id: 13,
		title: 'City Economic Department',
		description: faker.lorem.sentence(),
		location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
		orgType: 'local government',
		createdAt: new Date(),
		serviceTypes: ['funding'],
		updatedAt: new Date(),
		ownerId: admin._id,
		tags: [randomSeedTag(), randomSeedTag() ],
		resourceItems: [
			{
				title: `Main Street Loans Program`,
				description: faker.lorem.sentence(),
				location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
				resourceType: 'incentive',
				stages: ['existing'],
				serviceTypes: ['funding'],
				clusters: [randomCluster(), randomCluster()],
				schemaVersion: 0,
				//base
				createdAt: new Date(),
				updatedAt: new Date(),
				ownerId: admin._id,
				deleted: false,
			}
		],
		event: {
			title: 'What to know before you start',
			serviceTypes: ['workforce'],
			description: 'fsdafasf',
			location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
			stages: ['startup'],
			clusters: [randomCluster(), randomCluster()],
			tags: [],
			time: '12PM',
			date: faker.date.future(),
			usersAttending: [],
			schemaVersion: 0,
			numberAttending: 0,
			createdAt: new Date(),
			updatedAt: new Date(),
			ownerId: admin._id,
			deleted: false,
		}
	},
	{
		_id: 15,
		title: 'Local SCORE Office',
		description: faker.lorem.sentence(),
		location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
		orgType: 'local government',
		serviceTypes: ['funding'],
		createdAt: new Date(),
		updatedAt: new Date(),
		ownerId: admin._id,
		tags: [randomSeedTag(), randomSeedTag() ],
		resourceItems: [
			{
				title: `Free Business Mentor`,
				description: 'Need a business mentor to help you? Connect with one of SCOREs retired executives',
				location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
				resourceType: 'service',
				stages: ['existing'],
				serviceTypes: ['funding'],
				clusters: [randomCluster(), randomCluster()],
				schemaVersion: 0,
				//base
				createdAt: new Date(),
				updatedAt: new Date(),
				ownerId: admin._id,
				deleted: false,
			}
		],
		event: {
			title: 'What to know before you start',
			serviceTypes: ['workforce'],
			description: 'fsdafasf',
			location: `${faker.address.streetAddress()} ${faker.address.streetName()}`,
			stages: ['startup'],
			clusters: [randomCluster(), randomCluster()],
			tags: [],
			time: '12PM',
			date: faker.date.future(),
			usersAttending: [],
			schemaVersion: 0,
			numberAttending: 0,
			createdAt: new Date(),
			updatedAt: new Date(),
			ownerId: admin._id,
			deleted: false,
		}
	},
];

export { orgs }